In [5]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\kumar\Downloads\netflix_customer_churn (1).csv")
df=data.copy()

In [3]:
df.columns

Index(['customer_id', 'age', 'gender', 'subscription_type', 'watch_hours',
       'last_login_days', 'region', 'device', 'monthly_fee', 'churned',
       'payment_method', 'number_of_profiles', 'avg_watch_time_per_day',
       'favorite_genre'],
      dtype='str')

In [4]:
df.head(5)

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

In [5]:
df.describe()

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,43.847400,11.649450,30.089800,13.683400,0.503000,3.024400,0.874800
std,15.501128,12.014654,17.536078,3.692062,0.500041,1.415841,2.619824
min,18.000000,0.010000,0.000000,8.990000,0.000000,1.000000,0.000000
25%,30.000000,3.337500,15.000000,8.990000,0.000000,2.000000,0.110000
50%,44.000000,8.000000,30.000000,13.990000,1.000000,3.000000,0.290000
75%,58.000000,16.030000,45.000000,17.990000,1.000000,4.000000,0.720000
max,70.000000,110.400000,60.000000,17.990000,1.000000,5.000000,98.420000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             5000 non-null   str
 1   age                     5000 non-null   int64
 2   gender                  5000 non-null   str
 3   subscription_type       5000 non-null   str
 4   watch_hours             5000 non-null   float64
 5   last_login_days         5000 non-null   int64
 6   region                  5000 non-null   str
 7   device                  5000 non-null   str
 8   monthly_fee             5000 non-null   float64
 9   churned                 5000 non-null   int64
 10  payment_method          5000 non-null   str
 11  number_of_profiles      5000 non-null   int64
 12  avg_watch_time_per_day  5000 non-null   float64
 13  favorite_genre          5000 non-null   str
dtypes: float64(3), int64(4), str(7)
memory usage: 547.0 KB

In [15]:
df.shape

(5000, 14)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["gender"].value_counts()

gender
Female    1711
Male      1654
Other     1635
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded = encoder.fit_transform(df[["gender"]])

In [19]:
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["gender"]))

In [21]:
df=pd.concat([df, encoded_df], axis=1)

In [25]:
df.drop(columns=["gender"], inplace=True)

In [30]:
df["subscription_type"].value_counts()

subscription_type
Premium     1693
Basic       1661
Standard    1646
Name: count, dtype: int64

In [31]:
encoder2= OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded2= encoder.fit_transform(df[["subscription_type"]])
encoded_df2= pd.DataFrame(encoded2, columns=encoder.get_feature_names_out(["subscription_type"]))
encoded_df2.head(5)

,subscription_type_Basic,subscription_type_Premium,subscription_type_Standard
0,1.0,0.0,0.0
1,0.0,0.0,1.0
2,0.0,0.0,1.0
3,0.0,1.0,0.0
4,0.0,0.0,1.0

In [32]:
df=pd.concat([df, encoded_df2], axis=1)

In [39]:
df

,customer_id,age,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre,gender_Female,gender_Male,gender_Other
0,a9b75100-82a8-427a-a208-72f24052884a,51,0.0,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action,0.0,0.0,1.0
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,1.0,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi,0.0,0.0,1.0
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,1.0,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama,1.0,0.0,0.0
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,2.0,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror,0.0,0.0,1.0
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,1.0,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,44f3ba44-b95d-4e50-a786-bac4d06f4a43,19,0.0,49.17,11,Europe,Desktop,8.99,0,Credit Card,4,4.10,Drama,1.0,0.0,0.0
4996,18779bcb-ba2b-41da-b751-e70b812061ec,67,0.0,9.24,2,North America,Desktop,8.99,0,PayPal,3,3.08,Documentary,1.0,0.0,0.0
4997,3f32e8c5-615b-4a3b-a864-db2688f7834f,66,1.0,16.55,49,South America,Desktop,13.99,1,Debit Card,2,0.33,Action,0.0,1.0,0.0
4998,7b0ad82d-6571-430e-90f4-906259e0e89c,59,0.0,9.12,3,Europe,Laptop,8.99,0,Credit Card,4,2.28,Sci-Fi,1.0,0.0,0.0
4999,82aeef39-ddb0-40ad-bae1-5c436e0cf042,57,0.0,1.62,17,Africa,Mobile,8.99,1,Crypto,2,0.09,Action,0.0,1.0,0.0

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder
# encoder3= OrdinalEncoder(categories=[["Basic", "Standard", "Premium"]])
# df["subscription_type"] = encoder3.fit_transform(
#     df[["subscription_type"]]
# )

In [ ]:
# df.drop(columns=["subscription_type_Basic", "subscription_type_Premium", "subscription_type_Standard"], inplace=True)

In [40]:
df["region"].value_counts()

region
South America    873
Europe           867
North America    851
Asia             841
Africa           803
Oceania          765
Name: count, dtype: int64

In [41]:
df = pd.get_dummies(df, columns=["region"], dtype=int)

In [42]:
df

,customer_id,age,subscription_type,watch_hours,last_login_days,device,monthly_fee,churned,payment_method,number_of_profiles,...,favorite_genre,gender_Female,gender_Male,gender_Other,region_Africa,region_Asia,region_Europe,region_North America,region_Oceania,region_South America
0,a9b75100-82a8-427a-a208-72f24052884a,51,0.0,14.73,29,TV,8.99,1,Gift Card,1,...,Action,0.0,0.0,1.0,1,0,0,0,0,0
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,1.0,0.70,19,Mobile,13.99,1,Gift Card,5,...,Sci-Fi,0.0,0.0,1.0,0,0,1,0,0,0
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,1.0,16.32,10,TV,13.99,0,Crypto,2,...,Drama,1.0,0.0,0.0,0,1,0,0,0,0
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,2.0,4.51,12,TV,17.99,1,Crypto,2,...,Horror,0.0,0.0,1.0,0,0,0,0,1,0
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,1.0,1.89,13,Mobile,13.99,1,Crypto,2,...,Action,0.0,0.0,1.0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,44f3ba44-b95d-4e50-a786-bac4d06f4a43,19,0.0,49.17,11,Desktop,8.99,0,Credit Card,4,...,Drama,1.0,0.0,0.0,0,0,1,0,0,0
4996,18779bcb-ba2b-41da-b751-e70b812061ec,67,0.0,9.24,2,Desktop,8.99,0,PayPal,3,...,Documentary,1.0,0.0,0.0,0,0,0,1,0,0
4997,3f32e8c5-615b-4a3b-a864-db2688f7834f,66,1.0,16.55,49,Desktop,13.99,1,Debit Card,2,...,Action,0.0,1.0,0.0,0,0,0,0,0,1
4998,7b0ad82d-6571-430e-90f4-906259e0e89c,59,0.0,9.12,3,Laptop,8.99,0,Credit Card,4,...,Sci-Fi,1.0,0.0,0.0,0,0,1,0,0,0
4999,82aeef39-ddb0-40ad-bae1-5c436e0cf042,57,0.0,1.62,17,Mobile,8.99,1,Crypto,2,...,Action,0.0,1.0,0.0,1,0,0,0,0,0

In [43]:
df['device'].value_counts()

device
Tablet     1048
Laptop     1006
Mobile     1004
TV          993
Desktop     949
Name: count, dtype: int64

In [45]:
df = pd.get_dummies(df, columns=["device"], dtype=int)

In [57]:
df

,customer_id,age,subscription_type,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day,gender_Female,...,payment_method_Debit Card,payment_method_Gift Card,payment_method_PayPal,favorite_genre_Action,favorite_genre_Comedy,favorite_genre_Documentary,favorite_genre_Drama,favorite_genre_Horror,favorite_genre_Romance,favorite_genre_Sci-Fi
0,a9b75100-82a8-427a-a208-72f24052884a,51,0.0,14.73,29,8.99,1,1,0.49,0.0,...,0,1,0,1,0,0,0,0,0,0
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,1.0,0.70,19,13.99,1,5,0.03,0.0,...,0,1,0,0,0,0,0,0,0,1
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,1.0,16.32,10,13.99,0,2,1.48,1.0,...,0,0,0,0,0,0,1,0,0,0
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,2.0,4.51,12,17.99,1,2,0.35,0.0,...,0,0,0,0,0,0,0,1,0,0
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,1.0,1.89,13,13.99,1,2,0.13,0.0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,44f3ba44-b95d-4e50-a786-bac4d06f4a43,19,0.0,49.17,11,8.99,0,4,4.10,1.0,...,0,0,0,0,0,0,1,0,0,0
4996,18779bcb-ba2b-41da-b751-e70b812061ec,67,0.0,9.24,2,8.99,0,3,3.08,1.0,...,0,0,1,0,0,1,0,0,0,0
4997,3f32e8c5-615b-4a3b-a864-db2688f7834f,66,1.0,16.55,49,13.99,1,2,0.33,0.0,...,1,0,0,1,0,0,0,0,0,0
4998,7b0ad82d-6571-430e-90f4-906259e0e89c,59,0.0,9.12,3,8.99,0,4,2.28,1.0,...,0,0,0,0,0,0,0,0,0,1
4999,82aeef39-ddb0-40ad-bae1-5c436e0cf042,57,0.0,1.62,17,8.99,1,2,0.09,0.0,...,0,0,0,1,0,0,0,0,0,0

In [47]:
df['payment_method'].value_counts()

payment_method
Debit Card     1030
PayPal         1026
Crypto          995
Gift Card       976
Credit Card     973
Name: count, dtype: int64

In [49]:
df = pd.get_dummies(df, columns=['payment_method'], dtype=int)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 5000 non-null   str
 1   age                         5000 non-null   int64
 2   subscription_type           5000 non-null   float64
 3   watch_hours                 5000 non-null   float64
 4   last_login_days             5000 non-null   int64
 5   monthly_fee                 5000 non-null   float64
 6   churned                     5000 non-null   int64
 7   number_of_profiles          5000 non-null   int64
 8   avg_watch_time_per_day      5000 non-null   float64
 9   gender_Female               5000 non-null   float64
 10  gender_Male                 5000 non-null   float64
 11  gender_Other                5000 non-null   float64
 12  region_Africa               5000 non-null   int64
 13  region_Asia                 5000 non-null   int64
 14  region_Europe               5000 non-null   int64
 15  region_North America        5000 non-null   int64
 16  region_Oceania              5000 non-null   int64
 17  region_South America        5000 non-null   int64
 18  device_Desktop              5000 non-null   int64
 19  device_Laptop               5000 non-null   int64
 20  device_Mobile               5000 non-null   int64
 21  device_TV                   5000 non-null   int64
 22  device_Tablet               5000 non-null   int64
 23  payment_method_Credit Card  5000 non-null   int64
 24  payment_method_Crypto       5000 non-null   int64
 25  payment_method_Debit Card   5000 non-null   int64
 26  payment_method_Gift Card    5000 non-null   int64
 27  payment_method_PayPal       5000 non-null   int64
 28  favorite_genre_Action       5000 non-null   int64
 29  favorite_genre_Comedy       5000 non-null   int64
 30  favorite_genre_Documentary  5000 non-null   int64
 31  favorite_genre_Drama        5000 non-null   int64
 32  favorite_genre_Horror       5000 non-null   int64
 33  favorite_genre_Romance      5000 non-null   int64
 34  favorite_genre_Sci-Fi       5000 non-null   int64
dtypes: float64(7), int64(27), str(1)
memory usage: 1.3 MB

In [54]:
df = pd.get_dummies(df, columns=['favorite_genre'], dtype=int)

In [65]:
for col in df.columns:
    if df[col].dtype == 'string':
        print(col)

In [64]:
df.drop(columns=["customer_id"], inplace=True)

In [66]:
df.head(3)

,age,subscription_type,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day,gender_Female,gender_Male,...,payment_method_Debit Card,payment_method_Gift Card,payment_method_PayPal,favorite_genre_Action,favorite_genre_Comedy,favorite_genre_Documentary,favorite_genre_Drama,favorite_genre_Horror,favorite_genre_Romance,favorite_genre_Sci-Fi
0,51,0.0,14.73,29,8.99,1,1,0.49,0.0,0.0,...,0,1,0,1,0,0,0,0,0,0
1,47,1.0,0.70,19,13.99,1,5,0.03,0.0,0.0,...,0,1,0,0,0,0,0,0,0,1
2,27,1.0,16.32,10,13.99,0,2,1.48,1.0,0.0,...,0,0,0,0,0,0,1,0,0,0

In [67]:
df.to_csv("cleaned_netflix_data.csv", index=False)